name: Nosetests

on: [pull_request]

jobs:
  nose_tests_lvl2:
    runs-on: [self-hosted, linux, heavy]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
      with:
        path: main_class
    - name: Checkout reference 🛎️
      uses: actions/checkout@v4
      with:
        ref: master
        path: ref_class
    - name: Create virtual Python environment
      run: |
        rm -rf venv
        DEB_PYTHON_INSTALL_LAYOUT='deb' python -m virtualenv venv --system-site-packages
        source venv/bin/activate
        pip install --upgrade setuptools pytest
        deactivate
    - name: make
      run: source venv/bin/activate && cd main_class && pip install . && deactivate
    - name: make reference
      run: |
        source venv/bin/activate
        cd ref_class
        sed -i.bak "s/Extension('classy'/Extension('classyref'/g" setup.py
        sed -i.bak 's/"classy-community"/"classy-community-ref"/g' pyproject.toml
        pip install .
        deactivate
    - name: Testing 🤖
      run: |
        source venv/bin/activate
        cd main_class/python
        COMPARE_OUTPUT_REF=1 TEST_LEVEL=2 python -m pytest -v -m test_scenario test_class.py
        deactivate
    - name: Remove virtual Python environment
      if: success() || failure()
      run: rm -rf venv
    - name: Upload plots 📤
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
          name: NewtonianVsSynchronousPlots
          path: main_class/python/faulty_figs
